•••

diff --git a/pcmi-twa/gradlew b/pcmi-twa/gradlew
--- a/pcmi-twa/gradlew
+++ b/pcmi-twa/gradlew
@@ -1,3 +1,38 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
-exec "$JAVACMD" "$@"
+# Find java binary
+if [ -n "$JAVA_HOME" ] ; then
+    JAVACMD="$JAVA_HOME/bin/java"
+else
+    JAVACMD="java"
+fi
+
+if [ ! -x "$JAVACMD" ] ; then
+    echo "Error: JAVA_HOME is not defined correctly."
+    echo "Cannot execute $JAVACMD"
+    exit 1
+fi
+
+# Add default JVM options here
+DEFAULT_JVM_OPTS=""
+
+APP_NAME="Gradle"
+APP_BASE_NAME=`basename "$0"`
+
+# Use the maximum available, or set MAX_FD != -1 to use that value.
+MAX_FD="maximum"
+
+warn () {
+    echo "$*"
+}
+
+die () {
+    echo
+    echo "$*"
+    echo
+    exit 1
+}
+
+exec "$JAVACMD" $DEFAULT_JVM_OPTS \
+  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
+  org.gradle.wrapper.GradleWrapperMain "$@"
